name: Build Executable

on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
            
     # - name: Install Dependencies
     #   run: |
     #     pip install -r requirements.txt -r requirements-dev.txt
          
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: schedule_fixer
          onefile: true
          enable-plugins: tk-inter
          disable-console: true
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ScheduleFixer-${{ runner.os }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
